name: 4. Build Tauri App for ArchLinux

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build-tauri-arch:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up non-root user & sudo (makepkg doesnt allow root)
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm sudo git base-devel
          useradd -m -G wheel builduser
          echo "builduser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

      - name: Install Tauri build deps
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed \
            cairo desktop-file-utils gdk-pixbuf2 glib2 gtk3 \
            hicolor-icon-theme libsoup pango webkit2gtk-4.1 \
            openssl appmenu-gtk-module libappindicator-gtk3 librsvg \
            curl rustup nodejs npm

      - name: Extract app version
        run: |
          VERSION=$(node -p "require('./package.json').version || '0.0.0'")
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create PKGBUILD file
        run: |
          cat << 'EOF' > PKGBUILD
          # Maintainer: Sakura Yumine <i@nanoka.top>
          pkgname="pixiv-viewer"
          pkgver=PLACEHOLDER_VERSION
          pkgrel=1
          pkgdesc="Yet Another Pixiv Illust&Novel Viewer / 又一个 Pixiv 阅览工具"
          arch=('x86_64')
          url="https://github.com/asadahimeka/pixiv-viewer-app"
          license=('MIT')
          depends=('cairo' 'desktop-file-utils' 'gdk-pixbuf2' 'glib2' 'gtk3' 'hicolor-icon-theme' 'libsoup' 'pango' 'webkit2gtk-4.1')
          makedepends=('git' 'openssl' 'appmenu-gtk-module' 'libappindicator-gtk3' 'librsvg' 'rustup' 'nodejs' 'npm')
          options=('!lto' '!strip' '!debug')
          source=()
          sha256sums=()
          prepare() {
            echo Node.js $(node -v)
            echo npm $(npm -v)
            npm i -g pnpm
            echo pnpm $(pnpm -v)
            rustup update stable
            rustup default stable
            rustc --version
            ls -la ..
          }
          build() {
            cd ..
            pnpm install
            pnpm tauri build -v -b deb
          }
          package() {
            cd ..
            cp -a src-tauri/target/release/bundle/deb/Pixiv-Viewer_*/data/* "${pkgdir}"
          }
          EOF
          sed -i "s/PLACEHOLDER_VERSION/$APP_VERSION/g" PKGBUILD

      - name: Run makepkg
        run: |
          chown -R builduser:builduser .
          sudo -u builduser bash -c "
            echo 'VUE_APP_DEF_HIBIAPI_MAIN=${{ secrets.VUE_APP_DEF_HIBIAPI_MAIN }}' > .env
            echo 'VUE_APP_PXIMG_PROXYS=${{ secrets.VUE_APP_PXIMG_PROXYS }}' >> .env
            echo 'VUE_APP_DEF_PXIMG_MAIN=${{ secrets.VUE_APP_DEF_PXIMG_MAIN }}' >> .env
            echo 'VUE_APP_HIBIAPI_ALTS=${{ secrets.VUE_APP_HIBIAPI_ALTS }}' >> .env
            echo 'VUE_APP_DEF_APP_API_PROXY=${{ secrets.VUE_APP_DEF_APP_API_PROXY }}' >> .env
            echo 'VUE_APP_APP_API_PROXYS=${{ secrets.VUE_APP_APP_API_PROXYS }}' >> .env
            echo 'VUE_APP_COMMON_PROXY=${{ secrets.VUE_APP_COMMON_PROXY }}' >> .env
            echo 'VUE_APP_UMAMI_ID=${{ secrets.VUE_APP_UMAMI_ID }}' >> .env
            echo 'VUE_APP_UMAMI_SRC=${{ secrets.VUE_APP_UMAMI_SRC }}' >> .env
            echo 'VUE_APP_COMMON_IMAGE_PROXY=${{ secrets.VUE_APP_COMMON_IMAGE_PROXY }}' >> .env
            echo 'VUE_APP_SILICON_CLOUD_API_KEY=${{ secrets.VUE_APP_SILICON_CLOUD_API_KEY }}' >> .env
            echo 'VUE_APP_PLATFORM=tauri' >> .env
            echo 'BROWSERSLIST_ENV=tauri' >> .env
            makepkg --printsrcinfo > .SRCINFO
            makepkg -sf --noconfirm
          "

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          tag_name: draft_v_${{ env.APP_VERSION }}
          files: |
            *.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
